ci: :green_heart: debugging coverage upload

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -30,6 +30,12 @@ jobs:
           export PATH="$HOME/.local/bin:$PATH"
           poetry run pytest --cov=py2048 --cov-report=xml
 
+      - name: Check for coverage.xml
+        run: |
+          ls -lah
+          cat coverage.xml || echo "coverage.xml not found"
+
+
       - name: Upload coverage reports to Codecov
         uses: codecov/codecov-action@v5
         with:
